services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drive-in-theater
    volumes:
      - ./drive-in-theater:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  db:
    image: mysql:latest
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autosmozi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
